export const LOG_ACTIONS = {
  CREATE_EVENT: "CREATE_EVENT",
  UPDATE_EVENT: "UPDATE_EVENT",
  PUBLISH_EVENT: "PUBLISH_EVENT",
  CANCEL_EVENT: "CANCEL_EVENT",
  DELETE_EVENT: "DELETE_EVENT",
} as const;
